<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	 0xf192f5b8: ccl_err + 0xa5b8 (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0x90)
	 0xf193276b: ccl_err + 0xd76b (_Z14err_terminatorv + 0x8a)
	 0xeeeb507e: dinkum_alt + 0x1707e (_ZSt9terminatev + 0x1e)
	 0xedf7aaab: stdc++.so.6 + 0xb0aab (__cxa_rethrow + 0x5b)
	 0xf0cf6fbd: QtCore.so.4 + 0x17cfbd (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x36d)
	 0xf0cfbd0f: QtCore.so.4 + 0x181d0f (_ZN16QCoreApplication4execEv + 0xaf)
	 0xf0fa6507: QtGui.so.4 + 0x154507 (_ZN12QApplication4execEv + 0x27)
	  0x804e45f: quartus + 0x645f (__gxx_personality_v0 + 0x367)
	 0xf1f75908: ccl_msg + 0x23908 (_Z15msg_main_threadPv + 0x18)
	 0xf18e9f9e: ccl_thr + 0x5f9e (thr_final_wrapper + 0xe)
	 0xf1f76625: ccl_msg + 0x24625 (_Z18msg_thread_wrapperPFPvS_ES_ + 0x6c)
	  0x805de1d: quartus + 0x15e1d (_Z18mem_thread_wrapperPFPvS_ES_ + 0xdd)
	 0xf1934fd8: ccl_err + 0xffd8 (_Z18err_thread_wrapperPFPvS_ES_ + 0x2a)
	 0xf18ea3fa: ccl_thr + 0x63fa (thr_thread_wrapper + 0x2f)
	 0xf1f88e9a: ccl_msg + 0x36e9a (_Z12msg_exe_mainiPPKcPFiiS1_E + 0xb7)
	  0x804e531: quartus + 0x6531 (__gxx_personality_v0 + 0x439)
	 0xedbf3bc3: c.so.6 + 0x24bc3 (__libc_start_call_main + 0x73)
	 0xedbf3c88: c.so.6 + 0x24c88 (__libc_start_main + 0x88)
	  0x804e311: quartus + 0x6311 (__gxx_personality_v0 + 0x219)
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Mon Jul 29 08:29:12 2024
</date>
<version>Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition</version>
</internal_error>